travis:
  secure:
    BINSTAR_TOKEN: AyiMAVWbEyJ/hkL0TCuhbZ2owxrtm6t75k40Ev6p8z+JyhHUddMZHnFQeL0jEYG7GpwohYMBhhYoSO+8B+MjLZOr4X84rtcsm2aM/UT5CPps85W76UDWBe84welavtks4D0XoakegMKYzA1N9gtJIQGwWWPFCUW8js8tCzztgNW/pwXTDBYA323hAeK5Ij3MPvdji19DYTGOzps0Yymv2gkWRE3wC96Im0ZDJ3GFY5UWQNAQER0p0kp9rxFXv5fIM3SeeYCoWm3IIJ3VAdk+JOXVi4dH6FcZa78TNKuYimkEFPJKjzm3fdYqBilxb+N3AK1kc/3ygEgqRa6tyJ6otm/W+4mLHLtEokPxrulVjiAMnrs+7KbZre7bdwbbfS6SdeQOMojEy6iM7fRkPd4RNUieYxMj2NEuiXCizsQVrNjAl+JUcl2Pu2gsX7S/kD9ehfGjrcF2rPwfqDzaDsDDXFSM/6AjslNF6jH1TJmO48p3aT9umVD6lKyEcXNwt621jeDi0FTb6MZSWZK8vbktCrZgqYC9GyHNvtrQZoyjocI2f/eYh/IyIW5KzR1U00+Rv7gpPTjdACnRSJDcIH/AnDmcwpRST0LFG41elKGiQ2Yc6j2rNW6twO2b/+nYRWpeqBGU6dFQKkHKQqx3uA3meh7QNN73Vfa77sRn+zaZFcg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
